library(caTools)
library(nnet)
library(dplyr)
library(gmodels)
library(class)
mydata=read.csv("F:\\suneel\\project1\\hospital readmission1\\diabetic_cleaneddata.csv",header=TRUE,sep=",")
train_data=read.csv("F:\\suneel\\project1\\hospital readmission1\\train.csv",header=TRUE,sep=",")
test_data=read.csv("F:\\suneel\\project1\\hospital readmission1\\test.csv",header=TRUE,sep=",")

#=========================================================
#===============train data coverting char to num

train_data$readmitted=ifelse(train_data$readmitted=="<30","1",ifelse(train_data$readmitted==">30","2","3"))
train_data$race=ifelse(train_data$race=="AfricanAmerican","1",ifelse(train_data$race=="Asian","2",ifelse(train_data$race=="Caucasian","3",ifelse(train_data$race=="Hispanic","4","5"))))
train_data$gender=ifelse(train_data$gender=="Male","1",ifelse(train_data=="Female","2","3"))
train_data$age=ifelse(train_data$age=="[0-10)","1",ifelse(train_data$age=="[10-20)","2",ifelse(train_data$age=="[20-30)","3",ifelse(train_data$age=="[30-40)","4",ifelse(train_data$age=="[40-50)","5",ifelse(train_data$age=="[50-60)","6",ifelse(train_data$age=="[60-70)","7",ifelse(train_data$age=="[70-80)","8",ifelse(train_data$age=="[80-90)","9","10")))))))))
train_data$max_glu_serum=ifelse(train_data$max_glu_serum==">200","1",ifelse(train_data$max_glu_serum==">300","2",ifelse(train_data$max_glu_serum=="Norm","3","4")))
train_data$A1Cresult=ifelse(train_data$A1Cresult==">7","1",ifelse(train_data$A1Cresult==">8","2",ifelse(train_data$A1Cresult=="Norm","3","4")))
train_data$metformin=ifelse(train_data$metformin=="Up","1",ifelse(train_data$metformin=="Steady","2",ifelse(train_data$metformin=="Down","3","4")))
train_data$repaglinide=ifelse(train_data$repaglinide=="Up","1",ifelse(train_data$repaglinide=="Steady","2",ifelse(train_data$repaglinide=="Down","3","4")))
train_data$nateglinide=ifelse(train_data$nateglinide=="Up","1",ifelse(train_data$nateglinide=="Steady","2",ifelse(train_data$nateglinide=="Down","3","4")))
train_data$chlorpropamide=ifelse(train_data$chlorpropamide=="Up","1",ifelse(train_data$chlorpropamide=="Steady","2",ifelse(train_data$chlorpropamide=="Down","3","4")))
train_data$glimepiride=ifelse(train_data$glimepiride=="Up","1",ifelse(train_data$glimepiride=="Steady","2",ifelse(train_data$glimepiride=="Down","3","4")))
train_data$acetohexamide=ifelse(train_data$acetohexamide=="Steady","1","2")
train_data$glipizide=ifelse(train_data$glipizide=="up","1",ifelse(train_data$glipizide=="Steady","2",ifelse(train_data$glipizide=="Down","3","4")))
train_data$glyburide=ifelse(train_data$glyburide=="Up","1",ifelse(train_data$glyburide=="Steady","2",ifelse(train_data$glyburide=="Down","3","4")))
train_data$tolbutamide=ifelse(train_data$tolbutamide=="Steady","1","2")
train_data$pioglitazone=ifelse(train_data$pioglitazone=="Up","1",ifelse(train_data$pioglitazone=="Steady","2",ifelse(train_data$pioglitazone=="Down","3","4")))
train_data$rosiglitazone=ifelse(train_data$rosiglitazon=="Up","1",ifelse(train_data$rosiglitazon=="Steady","2",ifelse(train_data$rosiglitazon=="Down","3","4")))
train_data$acarbose=ifelse(train_data$acarbose=="Up","1",ifelse(train_data$acarbose=="Steady","2",ifelse(train_data$acarbose=="Down","3","4")))
train_data$miglitol=ifelse(train_data$miglitol=="Up","1",ifelse(train_data$miglitol=="Steady","2",ifelse(train_data$miglitol=="Down","3","4")))
train_data$troglitazone=ifelse(train_data$troglitazone=="Steady","1","2")
train_data$tolazamide=ifelse(train_data$tolazamide=="Up","1",ifelse(train_data$tolazamide=="Steady","2","3"))
train_data$insulin=ifelse(train_data$insulin=="Up","1",ifelse(train_data$insulin=="Steady","2",ifelse(train_data$insulin=="Down","3","4")))
train_data$glyburide.metformin=ifelse(train_data$glyburide.metformin=="Up","1",ifelse(train_data$glyburide.metformin=="Steady","2",ifelse(train_data$glyburide.metformin=="Down","3","4")))
train_data$glipizide.metformin=ifelse(train_data$glipizide.metformin=="Steady","1","2")
train_data$glimepiride.pioglitazone=ifelse(train_data$glimepiride.pioglitazone=="Steady","1","2")
train_data$metformin.rosiglitazone=ifelse(train_data$metformin.rosiglitazone=="Steady","1","2")
train_data$metformin.pioglitazone=ifelse(train_data$metformin.pioglitazone=="Steady","1","2")
train_data$change=ifelse(train_data$change=="Ch","1","2")
train_data$diabetesMed=ifelse(train_data$diabetesMed=="Yes","1","2")


train_data$race=as.numeric(train_data$race)
train_data$gender=as.numeric(train_data$gender)
train_data$age=as.numeric(train_data$age)
train_data$max_glu_serum=as.numeric(train_data$max_glu_serum)
train_data$A1Cresult=as.numeric(train_data$A1Cresult)
train_data$metformin=as.numeric(train_data$metformin)
train_data$repaglinide=as.numeric(train_data$repaglinide)
train_data$nateglinide=as.numeric(train_data$nateglinide)
train_data$chlorpropamide=as.numeric(train_data$chlorpropamide)
train_data$glimepiride=as.numeric(train_data$glimepiride)
train_data$acetohexamide=as.numeric(train_data$acetohexamide)
train_data$glipizide=as.numeric(train_data$glipizide)
train_data$glyburide=as.numeric(train_data$glyburide)
train_data$tolbutamide=as.numeric(train_data$tolbutamide)
train_data$pioglitazone=as.numeric(train_data$pioglitazone)
train_data$rosiglitazone=as.numeric(train_data$rosiglitazone)
train_data$acarbose=as.numeric(train_data$acarbose)
train_data$miglitol=as.numeric(train_data$miglitol)
train_data$troglitazone=as.numeric(train_data$troglitazone)
train_data$tolazamide=as.numeric(train_data$tolazamide)
train_data$insulin=as.numeric(train_data$insulin)
train_data$glyburide.metformin=as.numeric(train_data$glyburide.metformin)
train_data$glipizide.metformin=as.numeric(train_data$glipizide.metformin)
train_data$glimepiride.pioglitazone=as.numeric(train_data$glimepiride.pioglitazone)
train_data$metformin.rosiglitazone=as.numeric(train_data$metformin.rosiglitazone)
train_data$metformin.pioglitazone=as.numeric(train_data$metformin.pioglitazone)
train_data$change=as.numeric(train_data$change)
train_data$diabetesMed=as.numeric(train_data$diabetesMed)
train_data$readmitted=as.numeric(train_data$readmitted)


#===========================================================================
#===============================converting test data char to numeric

test_data$readmitted=ifelse(test_data$readmitted=="<30","1",ifelse(test_data$readmitted==">30","2","3"))
test_data$race=ifelse(test_data$race=="AfricanAmerican","1",ifelse(test_data$race=="Asian","2",ifelse(test_data$race=="Caucasian","3",ifelse(test_data$race=="Hispanic","4","5"))))
test_data$gender=ifelse(test_data$gender=="Male","1",ifelse(test_data=="Female","2","3"))
test_data$age=ifelse(test_data$age=="[0-10)","1",ifelse(test_data$age=="[10-20)","2",ifelse(test_data$age=="[20-30)","3",ifelse(test_data$age=="[30-40)","4",ifelse(test_data$age=="[40-50)","5",ifelse(test_data$age=="[50-60)","6",ifelse(test_data$age=="[60-70)","7",ifelse(test_data$age=="[70-80)","8",ifelse(test_data$age=="[80-90)","9","10")))))))))
test_data$max_glu_serum=ifelse(test_data$max_glu_serum==">200","1",ifelse(test_data$max_glu_serum==">300","2",ifelse(test_data$max_glu_serum=="Norm","3","4")))
test_data$A1Cresult=ifelse(test_data$A1Cresult==">7","1",ifelse(test_data$A1Cresult==">8","2",ifelse(test_data$A1Cresult=="Norm","3","4")))
test_data$metformin=ifelse(test_data$metformin=="Up","1",ifelse(test_data$metformin=="Steady","2",ifelse(test_data$metformin=="Down","3","4")))
test_data$repaglinide=ifelse(test_data$repaglinide=="Up","1",ifelse(test_data$repaglinide=="Steady","2",ifelse(test_data$repaglinide=="Down","3","4")))
test_data$nateglinide=ifelse(test_data$nateglinide=="Up","1",ifelse(test_data$nateglinide=="Steady","2",ifelse(test_data$nateglinide=="Down","3","4")))
test_data$chlorpropamide=ifelse(test_data$chlorpropamide=="Up","1",ifelse(test_data$chlorpropamide=="Steady","2",ifelse(test_data$chlorpropamide=="Down","3","4")))
test_data$glimepiride=ifelse(test_data$glimepiride=="Up","1",ifelse(test_data$glimepiride=="Steady","2",ifelse(test_data$glimepiride=="Down","3","4")))
test_data$acetohexamide=ifelse(test_data$acetohexamide=="Steady","1","2")
test_data$glipizide=ifelse(test_data$glipizide=="up","1",ifelse(test_data$glipizide=="Steady","2",ifelse(test_data$glipizide=="Down","3","4")))
test_data$glyburide=ifelse(test_data$glyburide=="Up","1",ifelse(test_data$glyburide=="Steady","2",ifelse(test_data$glyburide=="Down","3","4")))
test_data$tolbutamide=ifelse(test_data$tolbutamide=="Up","1","2")
test_data$pioglitazone=ifelse(test_data$pioglitazone=="Up","1",ifelse(test_data$pioglitazone=="Steady","2",ifelse(test_data$pioglitazone=="Down","3","4")))
test_data$rosiglitazone=ifelse(test_data$rosiglitazon=="Up","1",ifelse(test_data$rosiglitazon=="Steady","2",ifelse(test_data$rosiglitazon=="Down","3","4")))
test_data$acarbose=ifelse(test_data$acarbose=="Up","1",ifelse(test_data$acarbose=="Steady","2",ifelse(test_data$acarbose=="Down","3","4")))
test_data$miglitol=ifelse(test_data$miglitol=="Up","1",ifelse(test_data$miglitol=="Steady","2",ifelse(test_data$miglitol=="Down","3","4")))
test_data$troglitazone=ifelse(test_data$troglitazone=="Steady","1","2")
test_data$tolazamide=ifelse(test_data$tolazamide=="Up","1",ifelse(test_data$tolazamide=="Steady","2","3"))
test_data$insulin=ifelse(test_data$insulin=="Up","1",ifelse(test_data$insulin=="Steady","2",ifelse(test_data$insulin=="Down","3","4")))
test_data$glyburide.metformin=ifelse(test_data$glyburide.metformin=="Up","1",ifelse(test_data$glyburide.metformin=="Steady","2",ifelse(test_data$glyburide.metformin=="Down","3","4")))
test_data$glipizide.metformin=ifelse(test_data$glipizide.metformin=="Steady","1","2")
test_data$glimepiride.pioglitazone=ifelse(test_data$glimepiride.pioglitazone=="Steady","1","2")
test_data$metformin.rosiglitazone=ifelse(test_data$metformin.rosiglitazone=="Steady","1","2")
test_data$metformin.pioglitazone=ifelse(test_data$metformin.pioglitazone=="Steady","1","2")
test_data$change=ifelse(test_data$change=="Ch","1","2")
test_data$diabetesMed=ifelse(test_data$diabetesMed=="Yes","1","2")


test_data$race=as.numeric(test_data$race)
test_data$gender=as.numeric(test_data$gender)
test_data$age=as.numeric(test_data$age)
test_data$max_glu_serum=as.numeric(test_data$max_glu_serum)
test_data$A1Cresult=as.numeric(test_data$A1Cresult)
test_data$metformin=as.numeric(test_data$metformin)
test_data$repaglinide=as.numeric(test_data$repaglinide)
test_data$nateglinide=as.numeric(test_data$nateglinide)
test_data$chlorpropamide=as.numeric(test_data$chlorpropamide)
test_data$glimepiride=as.numeric(test_data$glimepiride)
test_data$acetohexamide=as.numeric(test_data$acetohexamide)
test_data$glipizide=as.numeric(test_data$glipizide)
test_data$glyburide=as.numeric(test_data$glyburide)
test_data$tolbutamide=as.numeric(test_data$tolbutamide)
test_data$pioglitazone=as.numeric(test_data$pioglitazone)
test_data$rosiglitazone=as.numeric(test_data$rosiglitazone)
test_data$acarbose=as.numeric(test_data$acarbose)
test_data$miglitol=as.numeric(test_data$miglitol)
test_data$troglitazone=as.numeric(test_data$troglitazone)
test_data$tolazamide=as.numeric(test_data$tolazamide)
test_data$insulin=as.numeric(test_data$insulin)
test_data$glyburide.metformin=as.numeric(test_data$glyburide.metformin)
test_data$glipizide.metformin=as.numeric(test_data$glipizide.metformin)
test_data$glimepiride.pioglitazone=as.numeric(test_data$glimepiride.pioglitazone)
test_data$metformin.rosiglitazone=as.numeric(test_data$metformin.rosiglitazone)
test_data$metformin.pioglitazone=as.numeric(test_data$metformin.pioglitazone)
test_data$change=as.numeric(test_data$change)
test_data$diabetesMed=as.numeric(test_data$diabetesMed)
test_data$readmitted=as.numeric(test_data$readmitted)




train_data=train_data[,-c(37,38)]
test_data=test_data[,-c(37,38)]

#train_data$readmitted=ifelse(train_data$readmitted=="<30","lessthanthirty",ifelse(train_data$readmitted==">30","greaterthanthirty","NO"))
#test_data$readmitted=ifelse(test_data$readmitted=="<30","lessthanthirty",ifelse(test_data$readmitted==">30","greaterthanthirty","NO"))

#train_data$readmitted=as.factor(train_data$readmitted)
#test_data$readmitted=as.factor(test_data$readmitted)
str(train_data)
str(test_data)
head(train_data)

normalize=function(x){
  return((x-min(x))/(max(x)-min(x)))
}

prc_n <- as.data.frame(lapply(train_data, normalize))

train_labels <- train_data[, 45]
test_labels <- test_data[, 45]

modelknn=knn(train = train_data,test = test_data,k=10,prob = FALSE,use.all = TRUE,cl=train_labels)

CrossTable(x=test_labels,y=modelknn,prop.chisq = FALSE)

mean(test_data$readmitted==modelknn)

save(modelknn,file = "modelknn.rda")

